name: deploy-py-lambda
on:
  push:
    branches:
      - xmaster
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLI_PROD_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLI_PROD_KEY }}
          aws-region: us-east-1
        # Build inside Docker containers
      - run: sam build --use-container --config-env prod
        # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset -t templateProd.yaml
